apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes
type: application
version: 79.6.1
appVersion: v0.86.2
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 79.6.1
