apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes
type: application
version: 80.9.2
appVersion: v0.87.1
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 80.9.2
