---
ceph-csi-cephfs:
  csiConfig:
    - clusterID: d4e29dd1-9269-4510-b874-a12bd39c7194
      monitors:
        - "192.168.1.20"
        - "192.168.1.21"
        - "192.168.1.22"
      cephFS:
        subvolumeGroup: "kubernetes"

  # Set logging level for csi containers.
  # Supported values from 0 to 5. 0 for general useful logs,
  # 5 for trace level verbosity.
  # logLevel is the variable for CSI driver containers's log level
  logLevel: 5
  # sidecarLogLevel is the variable for Kubernetes sidecar container's log level
  sidecarLogLevel: 1
  # Log slow operations at the specified rate.
  # Operation is considered slow if it outlives its deadline.
  logSlowOperationInterval: 30s

  storageClass:
    # Specifies whether the Storage class should be created
    create: true
    name: csi-cephfs-sc
    # Annotations for the storage class
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"

    # String representing a Ceph cluster to provision storage from.
    # Should be unique across all Ceph clusters in use for provisioning,
    # cannot be greater than 36 bytes in length, and should remain immutable for
    # the lifetime of the StorageClass in use.
    clusterID: d4e29dd1-9269-4510-b874-a12bd39c7194
    # (required) CephFS filesystem name into which the volume shall be created
    # eg: fsName: myfs
    fsName: cephfs
    # (optional) Ceph pool into which volume data shall be stored
    # pool: <cephfs-data-pool>
    # For eg:
    # pool: "replicapool"
    pool: ""
    # (optional) Comma separated string of Ceph-fuse mount options.
    # For eg:
    # fuseMountOptions: debug
    fuseMountOptions: ""
    # (optional) Comma separated string of Cephfs kernel mount options.
    # Check man mount.ceph for mount options. For eg:
    # kernelMountOptions: readdir_max_bytes=1048576,norbytes
    kernelMountOptions: ""
    # (optional) The driver can use either ceph-fuse (fuse) or
    # ceph kernelclient (kernel).
    # If omitted, default volume mounter will be used - this is
    # determined by probing for ceph-fuse and mount.ceph
    # mounter: kernel
    mounter: "kernel"
    # (optional) Prefix to use for naming subvolumes.
    # If omitted, defaults to "csi-vol-".
    # volumeNamePrefix: "foo-bar-"
    volumeNamePrefix: ""

    # (optional) Instruct the plugin it has to encrypt the volume
    # By default it is disabled. Valid values are "true" or "false".
    # A string is expected here, i.e. "true", not true.
    # encrypted: "true"
    encrypted: ""

    # (optional) Use external key management system for encryption passphrases by
    # specifying a unique ID matching KMS ConfigMap. The ID is only used for
    # correlation to configmap entry.
    encryptionKMSID: ""

    # The secrets have to contain user and/or Ceph admin credentials.
    provisionerSecret: csi-cephfs-secret
    # If the Namespaces are not specified, the secrets are assumed to
    # be in the Release namespace.
    provisionerSecretNamespace: ""
    controllerExpandSecret: csi-cephfs-secret
    controllerExpandSecretNamespace: ""
    nodeStageSecret: csi-cephfs-secret
    nodeStageSecretNamespace: ""
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    mountOptions: []
    # Mount Options
    # Example:
    # mountOptions:
    #   - discard

  secret:
    # Specifies whether the secret should be created
    create: false

  # This is a sample configmap that helps define a Ceph configuration as required
  # by the CSI plugins.
  # Sample ceph.conf available at
  # https://github.com/ceph/ceph/blob/master/src/sample.ceph.conf Detailed
  # documentation is available at
  # https://docs.ceph.com/en/latest/rados/configuration/ceph-conf/
  cephconf: |
    [global]
      auth_cluster_required = cephx
      auth_service_required = cephx
      auth_client_required = cephx

      # ceph-fuse which uses libfuse2 by default has write buffer size of 2KiB
      # adding 'fuse_big_writes = true' option by default to override this limit
      # see https://github.com/ceph/ceph-csi/issues/1928
      fuse_big_writes = true

  # Array of extra objects to deploy with the release
  extraDeploy: []
